# Generated by Django 3.1.7 on 2021-03-28 14:11

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=2000)),
                ('number_of_comments', models.PositiveIntegerField(default=0, editable=False)),
                ('number_of_likes', models.PositiveIntegerField(default=0, editable=False)),
            ],
        ),
    ]
